spring:
  application:
    name: edutech
  datasource:
    url: "jdbc:postgresql://ep-odd-wind-a1fdpqf3-pooler.ap-southeast-1.aws.neon.tech/edutech?sslmode=require"
    username: neondb_owner
    password: npg_OihqepFY1nV8
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
springdoc:
  api-docs:
    path: api-docs
app:
  jwt:
    expiration: 3600000
    exclude_filter:
      - /api/users/login
      - /swagger-ui/**